replicaCount: 1

podAnnotations:
  prometheus.io/scrape: "true"

image:
  pullPolicy: Always
imagePullSecrets: gitlab-credentials

nameOverride: ""
fullnameOverride: ""
configmap: gagas-config
secret: gagas-secret

service:
  type: ClusterIP
  ports:
    - port: 80
      dstPort: 8080
      name: http

virtualserver:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaller:
  replicas:
    min: 1
    max: 4
  utilization:
    cpu: 80
    memory: 80

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /live/status
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /live/status
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3

serviceAccount:
  create: false
  annotations: {}

nodeSelector: {}