apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .dstPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
