{{- if .Values.virtualserver.enabled -}}
{{- $fullName := .Release.Name -}}
{{- $svcPort := index .Values.service.ports 0 -}}
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.virtualserver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.virtualserver.host | quote }}
  upstreams:  
    - name: {{ .Release.Name | quote }}
      service: {{ .Release.Name | quote }}
      port: {{ $svcPort.port }}
  routes:
  - path: {{ .Values.virtualserver.path }}

  - path: ~/(live)
    action:
      return:
        code: 404
        type: text/plain
        body: "not found"
{{- end }}
