apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: TCP
    {{- if $port.nodePort }}
    nodePort: {{ $port.nodePort }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
