name: Create and Push custom Helm Chart

on:
  push:
    tags:
      - '**'

jobs:
  create:
    name: Create Helm Package
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Rename tag version
        run: |
          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 'v[0-9]+\.[0-9]+\.[0-9]+' | sed "s@v@@")
          echo $TAG_VERSION
      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: .
          version: "1.0.0"
          packages_with_index: true
